### ISSUE TITLE
Titlebar color untouched in PWAs on MacOS

### ISSUE THREAD

**Issue by memeplex** [coldenate/build-a-theme#8]
Hi, nice plugin! May I ask you how do you manage to change the titlebar color in a PWA? I tried overriding the manifest but each time I launch RemNote it sets the theme-color meta element again. I noticed that your plugin changed the titlebar color, but I can't understand how.

**Comment by coldenate** [comment]
Hi! Thank you for reaching out. Could you please provide a screenshot of what the titlebar is? I am not sure we are thinking of the same thing. The plugin's goal is to provide simple customization over the palette of RemNote (so never really changing the actual CSS except for the colors.)

That said, I am happy to help you create a **Custom CSS Code Block** to perform this for you.

**Comment by memeplex** [comment]
Then probably when you change the palette it's they that are changing the titlebar.

The titlebar is like this (although for RemNote instead of Docs):

<img width="1280" alt="image" src="https://github.com/coldenate/build-a-theme/assets/2845433/4bcad0aa-a5f3-4d25-a359-3ae6ca0fe6c0">

**Comment by coldenate** [comment]
Okay. I will look into this. There's a chance it may not be able to be styled as I think that deals more with the application's configuration instead of the css.

**Comment by coldenate** [comment]
Unfortunately this is not something I can modify at the time. But I would love to see it happen in the future! I'll reopen if it ever comes to fruition.
